services:
  connection-machine:
    container_name: connection-machine
    build:
      context: .
    env_file:
      - .env
    environment:
      - CHROME_PORT=9225
    restart: always
    dns: 1.1.1.1
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
    volumes:
      - ./data:/app/data
