services:
  trel:
    container_name: trel
    build:
      context: .
    env_file:
      - .env
    environment:
      - CHROME_PORT=9225
    restart: always
    ports:
      - "127.0.0.1:9225:9225"
    dns: 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
    volumes:
      - ./data/trel-chrome:/app/data/trel-chrome

  xray:
    image: teddysun/xray:25.10.15
    container_name: xray
    restart: always
    dns: 1.1.1.1
    volumes:
      - ./data/xray:/etc/xray
