services:
  trel:
    container_name: trel
    build:
      context: .
    env_file:
      - .env
    environment:
      - CHROME_PORT=9225
    restart: unless-stopped
    ports:
      - "127.0.0.1:9225:9225"
    volumes:
      - ./data/trel-chrome:/app/data/trel-chrome

  xray:
    image: teddysun/xray:25.10.15
    container_name: xray
    restart: unless-stopped
    volumes:
      - ./data/xray:/etc/xray
